### ISSUE TITLE
Creating a mask layer on a fill layer crashes the app

### ISSUE THREAD

**Issue by jcostello** [armory3d/armorpaint#578] opened 2020-09-20 13:50 UTC
**ArmorPaint version:**
0.8 commit 1a27f5896404c9188090bae944823493aaf3ed93

**OS/device including version:**
Ubuntu 20.04
GT 1030

**Issue description:**
When creating a mask in a fill layer the app freezes

**Steps to reproduce:**
Add a material
Create a fill layer
Create a mask on the fill layer

```
Trace: TypeError: Cannot read property 'texpaint_mask' of undefined
    at Array.arm_render_Uniforms.linkTex (<anonymous>:23756:90)
    at Function.iron_object_Uniforms.setObjectConstants (<anonymous>:32937:29)
    at iron_object_MeshObject.render (<anonymous>:31664:25)
    at iron_RenderPath.submitDraw (<anonymous>:3993:44)
    at iron_RenderPath.drawMeshes (<anonymous>:3959:8)
    at Function.arm_render_RenderPathDeferred.drawGbuffer (<anonymous>:21949:37)
    at iron_RenderPath.arm_render_RenderPathDeferred.commands (<anonymous>:21740:32)
    at iron_RenderPath.renderFrame (<anonymous>:3791:8)
    at iron_object_CameraObject.renderFrame (<anonymous>:30452:26)
    at iron_Scene.renderFrame (<anonymous>:4716:16)
```

**Comment by luboslenco** [comment] 2020-09-20 17:23
Hm, unable to reproduce so far. Any chance the submodules of your armorpaint clone did not get updated? (eg. both `git pull origin master` and `git submodule update --init --recursive` are needed)

**Comment by jcostello** [comment] 2020-09-21 20:25
I will try and let you know

**Comment by jcostello** [comment] 2020-09-21 20:32
I pulled master again and update the submodules and got the same issue

**Comment by luboslenco** [comment] 2020-09-21 20:37
How do you create a fill layer?

**Comment by jcostello** [comment] 2020-09-21 20:47
I drag the material into the mesh.

**Comment by jcostello** [comment] 2020-09-21 20:49
I deleted armorpaint directory and clone it again and update modules and seems to work but I got the same error trying to delete a fill layer. I will try to reproduce

**Comment by jcostello** [comment] 2020-09-21 21:01
![Peek 2020-09-21 18-00](https://user-images.githubusercontent.com/1168582/93821120-84848e00-fc34-11ea-8eb3-4b3f543c5b30.gif)

**Comment by luboslenco** [comment] 2020-09-21 21:27
Nice, was able to reproduce with the height map! Pushed a fix at https://github.com/armory3d/armorpaint/commit/58800f77f847f1805651e9e6b126fff22a236077. Thanks for patience.

**Closed by luboslenco** 2020-09-21 21:27 UTC
Labels: bug

**Comment by jcostello** [comment] 2020-09-22 13:27
@luboslenco thank you. You are doing an amazing job. Thanks for listen the community. Is really nice to test your work and report to you :muscle:
