### ISSUE TITLE
Error when trying to download library in the cloud

### ISSUE THREAD

**Issue by alexanderferreira** [armory3d/armorpaint#864] opened 2021-04-14 23:12 UTC
![Error_ArmorPaint](https://user-images.githubusercontent.com/1265926/114791788-72e40e80-9d5d-11eb-8506-eb128c597a42.png)

Hi,

When I click on cloud, this error appears and does not download.

*ArmorPaint 0.8-6520875, Linux*

**Feature description:**

**Comment by MathemanFlo** [comment] 2021-04-15 08:32
I can not reproduce it in ArmorPaint.org - v0.8 (2021-04-15) - a8673d9 on Windows.
But what I realise is that ArmorPaint opens and instantly closes lots of terminal(?) windows. Especially if I go to materials/cc0 because there are lots of files. Meanwhile the computer becomes unresponsive because these windows get the focus. 
The high frequency of opening and closing the windows produces a strange "animation" in the taskbar. 
![ap](https://user-images.githubusercontent.com/28649121/114839175-c2feb780-9dd5-11eb-891b-9daccc7150bb.png)

**Comment by SneakyKittyGaming** [comment] 2021-05-05 00:29
I am also experiencing this issue on windows 10. No duplicate windows, everything works as normal, just cannot access the cloud.

**Comment by luboslenco** [comment] 2021-05-13 13:21
Should work better now in latest builds. Please let me know if there are still issues accessing the cloud.

**Comment by SneakyKittyGaming** [comment] 2021-05-13 18:00
> Should work better now in latest builds. Please let me know if there are still issues accessing the cloud.

Just tested on windows 10 with the new build and its working. Thank you!

**Comment by luboslenco** [comment] 2021-05-17 09:27
Great to hear, thanks!

**Closed by luboslenco** 2021-05-17 09:27 UTC
Labels: bug

**Comment by spamjim** [comment] 2021-06-30 16:37
I'm experiencing this issue ("check internet connection to access the cloud") on Win7. 

ArmorPaint.org - v0.8 (2021-06-16) - e72478b

The cmd.exe window displayed the following error (grabbed with a quick press of the printscreen button):

```

The term 'invoke-WebRequest' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:18
+ Invoke-WebRequest <<<< -Uri 'https://luboslenco.gotlab.io/armorpaint/index/html' -OutFile 'J:\PortableApps\ArmorPaint\.\data\\download.bin'
+ CategoryInfo " ObjectNotFound: (Invoke-WebRequest:String) [], CommandNotFoundException
+ FullyQualifiedErrorId : CommandNotFoundException  
```

ArmorPaint\.\data\\download.bin seems like an odd path
