### ISSUE TITLE
Crush when hover the cursor above perspective or orthographic camera options.

### ISSUE THREAD

**Issue by infinder** [armory3d/armorpaint#644] opened 2020-10-23 16:39 UTC
Strange behavior of the program. From the menu select camera. Then place the cursor over the Perspective or Orthographic option(don't click anything). crush!!!

**Comment by luboslenco** [comment] 2020-10-23 17:13
Sorry I am not sure I follow - can you post a screenshot? Which armorpaint version? Which OS?

**Comment by MathemanFlo** [comment] 2020-10-23 18:03
Can you read those dump files and extract useful information from them? Because I could non deterministically reproduce this issue. I switched from orthographic to perspective and on menu hover ArmorPaint crashed (commit 7d31407).
[kinc.dmp.zip](https://github.com/armory3d/armorpaint/files/5431052/kinc.dmp.zip)

**Comment by infinder** [comment] 2020-10-23 18:08
windows 10, intel HD 620
ArmorPaint - v0.8 (2020-10-23) - 7d31407

Put the cursor where the screenshot shows. Don't click perspective, just put the cursor above it and wait.. The same with orthographic option.

![Clipboard041](https://user-images.githubusercontent.com/72331575/97038714-e3129400-1573-11eb-9418-7549dd18a96f.jpg)

**Comment by MathemanFlo** [comment] 2020-10-23 18:15
Yes I can reproduce this, too on win10 and Linux. Waiting for 1-2s and ArmorPaint crashes.

**Comment by luboslenco** [comment] 2020-10-23 19:16
Nice! Pushed a fix at https://github.com/armory3d/zui/commit/fb942132ace014b275eef1d407111e0b2da8ff9e. Make sure to update submodules as well.

```
git pull origin master
git submodule update --init --recursive
```

**Closed by luboslenco** 2020-10-23 19:16 UTC
Labels: bug
