### ISSUE TITLE
iOS deployment broken (?)

### ISSUE THREAD

**Issue by inseyven** [armory3d/armorpaint#1390] opened 2022-05-02 21:36 UTC
I always end up with this error when I try to build ArmorPaint for iOS with Xcode
![image](https://user-images.githubusercontent.com/25097644/166331632-626cc1fb-0259-44fd-ad7d-320e4e6882dc.png)
![image](https://user-images.githubusercontent.com/25097644/166331642-e5d8de7c-32e4-4ffa-90e9-e0e9ea682ecc.png)

**Comment by MathemanFlo** [comment] 2022-05-03 05:52
I think it is a duplicate of https://github.com/armory3d/armorpaint/issues/1283

**Comment by luboslenco** [comment] 2022-05-03 07:53
👍  Continue at https://github.com/armory3d/armorpaint/issues/1283.

**Closed by luboslenco** 2022-05-03 07:53 UTC
Labels: question
