### ISSUE TITLE
Bump node bug

### ISSUE THREAD

**Issue by AlexKiryanov** [armory3d/armorpaint#391] opened 2020-05-12 16:49 UTC
*Please specify your ArmorPaint version and OS.*
Win 64 v 0.8 2020.05.12
For some reason, in some places of the model this node is displayed normally, and in some messes a black spot.
![3](https://user-images.githubusercontent.com/65244629/81722147-a6e9ec00-9489-11ea-9bc8-df636965ff7f.jpg)

**Comment by luboslenco** [comment] 2020-08-09 20:11
Hello, thanks for report - I managed to reproduce this issue. Just to clarify, are you looking to implement custom bump node https://github.com/armory3d/armorpaint/issues/481 because of this issue? That will help me figuring out which issue should I investigate first.

**Comment by AlexKiryanov** [comment] 2020-08-09 20:46
Good evening Lubos! Damn, I'm so glad you wrote to me.

In the beginning, yes. I thought it would be easy to make such a node, since the code is already there, I just need to figure out how to fit it to the armor. I thought it was great to do it, and not bother you with it, so that you can solve more difficult issues. But in the end.
I realized that this is not so simple, since I did not find any binding in the sampler 2D in the code. For a hike, this is somehow embedded deeply into the program code)
 
Now I think so. It depends on how long it will take you to repair a standard node. If you quickly solve the standard node, then go ahead! If not, then probably yes (in any case, in the future, the question about the sampler in the custom node will arise)
Because I have more ideas. For example, different shapes for procedural materials.

I just want to help you somehow. And I also want the armor to work correctly. But I understand that I am wasting your time.
By the way, I noticed a new assembly, viar? Mmm very interesting (my friend has viar glasses), but I could not assemble it, it gives an error when compiling. I can write a report to the github about this.

**Comment by AlexKiryanov** [comment] 2020-08-27 19:59
Good evening again! There is no good news on this issue? Well, or on the issue of texture offset  in a custom node?

**Comment by AlexKiryanov** [comment] 2021-01-29 17:37
Lubos, good evening! sorry to remind you, I see how many edits and additions you are doing now. but can you find a little time to solve this problem? Mmmmm?

**Comment by luboslenco** [comment] 2021-02-01 12:02
Apologizes for taking so long, pushed a fix now at https://github.com/armory3d/armorpaint/commit/e830eee952e4e883742e72f93df96bea4eeffc48. Will continue to improve the bump node quality but at least the black spots should be gone now. Thanks for the report!

![cap](https://user-images.githubusercontent.com/3685704/106455786-f4314200-648c-11eb-964d-1b060a8ece93.png)

**Closed by luboslenco** 2021-02-01 12:02 UTC
Labels: bug

**Comment by AlexKiryanov** [comment] 2021-02-01 12:06
Good afternoon) oh this is great news) thank you very much! do not
apologize, I see how much you are doing) especially in recent months))

пн, 1 февр. 2021 г., 15:02 Lubos Lenco <notifications@github.com>:
