### ISSUE TITLE
Strange error when rotating in viewport

### ISSUE THREAD

**Issue by paolohuesp** [armory3d/armorpaint#1136] opened 2021-09-29 01:20 UTC
*ArmorPaint 0.8-c0978d1, Windows*

Issue description: 
This error occurred to me while I was painting and suddenly when I wanted to rotate, what it does is zoom very quickly while I rotate.
I have tried closing and reopening but it persists with only that file.

Steps to reproduce:
I would not know how to reproduce it, since it happened suddenly.

**Comment by MathemanFlo** [comment] 2021-09-29 08:49
I think this is similar to or a duplicate of #1131 and #1050.

**Comment by luboslenco** [comment] 2021-09-29 08:52
Continue at https://github.com/armory3d/armorpaint/issues/1050.

**Closed by luboslenco** 2021-09-29 08:52 UTC
Labels: bug
