### ISSUE TITLE
Painting vaules in fill layer mask issue

### ISSUE THREAD

**Issue by melvixiodf** [armory3d/armorpaint#822] opened 2021-02-15 13:54 UTC
Brushes with textures paint inconsistently or is this done on purpose to create some variety while painting. If I set the brush to paint white vaule for mask, the vaule isn't painted consistently, the vaules painted are all over the place:
![screenshot](https://user-images.githubusercontent.com/54470864/107953181-0df97b80-6f9b-11eb-99dc-2ace418e509b.gif)

This approach has its advantages. Maybe an accumulate option for the brushes with textures when you need to paint only white vaules?

**Comment by luboslenco** [comment] 2021-02-15 14:03
Hello, thanks for report! It looks like in your brush nodes you have a `Random` node assigned to `Brush Output - Angle`, hence the randomness / inconsistency.

If the issue still persists please let me know the `ArmorPaint version`, `OS` and `Steps to reproduce` and I will be able to fix it asap.

**Closed by luboslenco** 2021-02-15 14:03 UTC
Labels: bug

**Comment by melvixiodf** [comment] 2021-02-15 14:50
ArmorPaint v0.8 (2021-02-09)-552b6b3
Windows-Direct3D12
It still exist after removing the random from angle. I was using the jitter brush setup
When painting white with a wacom pen, lift the pen and paint again and the white vaule you painted before is erased with a new random vauled repainted over it. Each time you lift the pen, this happens. This happens when using a texture with the brush. I am using a black and white png texture. So it seems everytime, you lift and repaint, the black part of the texture used, paints black onto the surface erasing the white vaule painted before.
