### ISSUE TITLE
Color strokes messed up while painting

### ISSUE THREAD

**Issue by herb64** [armory3d/armorpaint#50] opened 2018-12-18 12:24 UTC
Just bought Armorpaint today version 0.5. Fujitsu Notebook, Windows 10 Pro, NVidia Quadro 3000M
Start software and just begin painting on the default cube - at some parts, color disappears when releasing the mouse button. If proceeding to paint, it gets more and more weird, not able to color the object completely. Also Fill tool does leave unpainted areas behind.

![armorp](https://user-images.githubusercontent.com/26320983/50160253-1a112200-02d9-11e9-990a-d8bbc8abfafe.gif)

I updated NVidia Driver to latest version, but this does not change anything. Also tested the Gun example - when painting on it, it get's completely messed up.

Looks like the exported texture (checked base color) is ok, so it's just a rendering problem, so that parts of the mesh turn black.

**Comment by herb64** [comment] 2018-12-31 07:53
Hello, I tested a Fedora27 installation on the same hardware, the problem did not appear.

**Comment by Cribby** [comment] 2019-02-23 14:52
This issue is happening on my computer as well- Windows 10 AMD Radeon HD 6800 series graphics card. I'm going to try the previous version and see if that works better. Would it have anything to do with the Visual C++ 2017 Redistributable x64 requirement or is this separate? I don't have that installed on my computer.

**Comment by luboslenco** [comment] 2019-02-28 18:03
Hm, any difference using the new 0.6 development build?
(Visual C++ 2017 Redistributable should not affect this.)

**Comment by herb64** [comment] 2019-03-01 07:56
With the 0.6 development build, the issue is solved on my system. I'll do some more testing, but playing with it, I was not able to reproduce this anymore. Thanks a lot.

**Comment by Cribby** [comment] 2019-03-02 21:34
I just tested the 0.6 build as well and the issue is fixed on my system. Thanks very much :-)

**Comment by luboslenco** [comment] 2019-03-08 18:11
Wohoo!

**Closed by luboslenco** 2019-03-08 18:11 UTC

**Comment by johnbourne** [comment] 2019-03-18 19:39
However, I see the problem (same as herb 64 showed above) on my MacBook Pro (2017). I'm running .6 ....
