### ISSUE TITLE
Armor Paint Library brushes and textures 

### ISSUE THREAD

**Issue by JJ-ind** [armory3d/armorpaint#351] opened 2020-04-02 04:10 UTC
I have seen on official website you are making an library 
i am new to this 
i have many decals and alpha brushes and textures 
i want to add it to the library , how can i do that.
i also have multiple hdris

**Comment by august0815** [comment] 2020-04-02 05:31
Yes would be cool

**Comment by JJ-ind** [comment] 2020-04-02 12:15
yes but i dont know how to add
i have 1000+ textures 
1200 alpha textures for brushes

**Comment by m0nsky** [comment] 2020-04-04 04:09
I was working on an open library for sharing armorpaint materials, however I ran into the problem that some (maybe all?) materials use absolute texture paths.

**Comment by Calinou** [comment] 2020-04-06 13:21
This is likely a duplicate of #177.

**Comment by JJ-ind** [comment] 2020-04-10 03:19
> This is likely a duplicate of #177.

not really 
i want to contribute my textures and brushes not materials

**Comment by JJ-ind** [comment] 2020-04-10 03:20
> This is likely a duplicate of #177.

not really 
i want to contribute to it 
its not a feature request but a pull i think
i am noob to github so i dont know how to contribute

**Comment by Calinou** [comment] 2020-04-10 07:03
#177 is an issue (a feature request in this case), not a pull request :wink:

**Comment by luboslenco** [comment] 2020-05-19 13:33
Sorry it's taking so long and many thanks for the help, really appreciate that. I am still working on the library feature - will post at https://github.com/armory3d/armorpaint/issues/177 as soon as possible!

**Closed by luboslenco** 2020-05-19 13:33 UTC
Labels: feature request
