### ISSUE TITLE
Crash the second time I open ArmorPaint or load a file after opening another project

### ISSUE THREAD

**Issue by SaraDark** [armory3d/armorpaint#769] opened 2021-01-18 15:51 UTC
Again: Crash the second time I open ArmorPaint or load a file after opening another project - Linux,
+ Randommly:
![image](https://user-images.githubusercontent.com/69405892/104936847-5d08bc80-59ad-11eb-9988-ac7442d0b7ba.png)

ArmorPaint.org - v0.8 (2021-01-15) - 30aff91

+ And on Linux Numpad not working correctly

**Comment by luboslenco** [comment] 2021-01-18 15:59
Can you provide steps to reproduce the issue? Can you launch ArmorPaint from terminal and paste the output?

> And on Linux Numpad not working correctly

Already reported at https://github.com/armory3d/armorpaint/issues/713.

**Comment by SaraDark** [comment] 2021-01-18 16:17
Randommly, eg. open, moce cube view, close, open then crash, but not always.
Its Randommly.

**Comment by luboslenco** [comment] 2021-01-18 16:18
> Can you launch ArmorPaint from terminal and paste the output?

**Comment by SaraDark** [comment] 2021-01-18 16:21
$ /opt/ArmorPaint/08/ArmorPaint
Uniform N not found.
Trace: TypeError: Cannot read property 'raw' of undefined
    at Ba.resize (krom_cache:190:17)
    at Ba.renderFrame (krom_cache:178:313)
    at pd.renderFrame (krom_cache:1307:11)
    at W.renderFrame (krom_cache:198:254)
    at Array.render (krom_cache:149:241)
    at Function.render (krom_cache:1531:295)
    at renderCallback (krom_cache:1533:4)
Trace: TypeError: Cannot read property 'raw' of undefined

...

Trace: TypeError: Cannot read property 'raw' of undefined
    at Ba.resize (krom_cache:190:17)
    at Ba.renderFrame (krom_cache:178:313)
    at pd.renderFrame (krom_cache:1307:11)
    at W.renderFrame (krom_cache:198:254)
    at Array.render (krom_cache:149:241)
    at Function.render (krom_cache:1531:295)
    at renderCallback (krom_cache:1533:4)
Trace: TypeError: Cannot read property 'raw' of undefined
    at Ba.resize (krom_cache:190:17)
    at Ba.renderFrame (krom_cache:178:313)
    at pd.renderFrame (krom_cache:1307:11)
    at W.renderFrame (krom_cache:198:254)
    at Array.render (krom_cache:149:241)
    at Function.render (krom_cache:1531:295)
    at renderCallback (krom_cache:1533:4)
Trace: TypeError: Cannot read property 'raw' of undefined
    at Ba.resize (krom_cache:190:17)
    at Ba.renderFrame (krom_cache:178:313)
    at pd.renderFrame (krom_cache:1307:11)
    at W.renderFrame (krom_cache:198:254)
    at Array.render (krom_cache:149:241)
    at Function.render (krom_cache:1531:295)
    at renderCallback (krom_cache:1533:4)
Trace: TypeError: Cannot read property 'raw' of undefined
    at Ba.resize (krom_cache:190:17)
    at Ba.renderFrame (krom_cache:178:313)
    at pd.renderFrame (krom_cache:1307:11)
    at W.renderFrame (krom_cache:198:254)
    at Array.render (krom_cache:149:241)
    at Function.render (krom_cache:1531:295)
    at renderCallback (krom_cache:1533:4)
Trace: TypeError: Cannot read property 'raw' of undefined
    at Ba.resize (krom_cache:190:17)
    at Ba.renderFrame (krom_cache:178:313)
    at pd.renderFrame (krom_cache:1307:11)
    at W.renderFrame (krom_cache:198:254)
    at Array.render (krom_cache:149:241)
    at Function.render (krom_cache:1531:295)
    at renderCallback (krom_cache:1533:4)
Trace: TypeError: Cannot read property 'raw' of undefined
    at Ba.resize (krom_cache:190:17)
    at Ba.renderFrame (krom_cache:178:313)
    at pd.renderFrame (krom_cache:1307:11)
    at W.renderFrame (krom_cache:198:254)
    at Array.render (krom_cache:149:241)
    at Function.render (krom_cache:1531:295)
    at renderCallback (krom_cache:1533:4)
Trace: TypeError: Cannot read property 'raw' of undefined
    at Ba.resize (krom_cache:190:17)
    at Ba.renderFrame (krom_cache:178:313)
    at pd.renderFrame (krom_cache:1307:11)
    at W.renderFrame (krom_cache:198:254)
    at Array.render (krom_cache:149:241)
    at Function.render (krom_cache:1531:295)
    at renderCallback (krom_cache:1533:4)
Trace: TypeError: Cannot read property 'raw' of undefined
    at Ba.resize (krom_cache:190:17)
    at Ba.renderFrame (krom_cache:178:313)
    at pd.renderFrame (krom_cache:1307:11)
    at W.renderFrame (krom_cache:198:254)
    at Array.render (krom_cache:149:241)
    at Function.render (krom_cache:1531:295)
    at renderCallback (krom_cache:1533:4)
Trace: TypeError: Cannot read property 'raw' of undefined
    at Ba.resize (krom_cache:190:17)
    at Ba.renderFrame (krom_cache:178:313)
    at pd.renderFrame (krom_cache:1307:11)
    at W.renderFrame (krom_cache:198:254)
    at Array.render (krom_cache:149:241)
    at Function.render (krom_cache:1531:295)
    at renderCallback (krom_cache:1533:4)
...

**Comment by luboslenco** [comment] 2021-01-19 11:39
I was not able to reproduce yet but pushed a fix attempt at https://github.com/armory3d/iron/commit/788c1764fc2356c1ef7bf0c50308753e05e2bb2c. New builds up soon. It the issue persists please let me know, include the project files, your ArmorPaint config, everything helps. Thanks!

**Closed by luboslenco** 2021-01-19 11:39 UTC
Labels: bug
