### ISSUE TITLE
Blur does not work for mask

### ISSUE THREAD

**Issue by SlincHD** [armory3d/armorpaint#1433] opened 2022-07-22 20:43 UTC
armorpaint 0.9
gumroad
win 10

idk what to say els the blur brush dosn't work at all

**Comment by Tyrannosaurus1234** [comment] 2022-08-17 04:21
Blur works for me on materials, but not masks.

**Comment by luboslenco** [comment] 2023-01-06 15:51
Pushed a fix for mask blur at https://github.com/armory3d/armorpaint/commit/27b1b58b01aa8b3f14c92a1ec8e51877034a5dac, thanks for report.

If blur still does not work please let me know steps to reproduce, will investigate.

**Closed by luboslenco** 2023-01-06 15:51 UTC
Labels: bug
