### ISSUE TITLE
Fix importing non-convex polygons from .obj/.fbx/.blend

### ISSUE THREAD

**Issue by MrMinimal** [armory3d/armorpaint#228] opened 2019-12-01 16:26 UTC
**ArmorPaint version:** ArmorPaint_07dev_win64
**Blender version:** 2.81

File in question: 
[Mfcd.zip](https://github.com/armory3d/armorpaint/files/3908427/Mfcd.zip)

**How it's supposed to look like:**
![image](https://user-images.githubusercontent.com/8739690/69916754-517fcc80-145f-11ea-8031-5935099b3895.png)

**And here is what it looks like after importing into ArmorPaint:**

.FBX:
![image](https://user-images.githubusercontent.com/8739690/69916766-6a887d80-145f-11ea-8bfc-110727a26d28.png)

.obj:
![image](https://user-images.githubusercontent.com/8739690/69916780-88ee7900-145f-11ea-98bb-313ca59695d8.png)

.blend:
![image](https://user-images.githubusercontent.com/8739690/69916786-9146b400-145f-11ea-91dc-f76a42b04128.png)

If i can provider further info, please tell me to do so!

Love the editor ❤

**Comment by Granada1** [comment] 2019-12-01 16:42
Have you tried welding vertices on the model ,I have had similar problems in other software and welding helped

**Comment by MrMinimal** [comment] 2019-12-01 17:19
@Granada1 What do you mean by welding? That model is very simple in terms of modeling, just cubes and some modifiers applied.

**Comment by Granada1** [comment] 2019-12-01 18:08
My apologies I thought it was a obj file you exported ,I don’t use Blender

**Comment by luboslenco** [comment] 2019-12-10 13:11
Many thanks for sharing the file! It looks like the issue is triangulating non-convex polygons when importing the file - looking into a fix. As a (temporary) workaround, enabling `Triangulate Faces` option during `.obj` export in Blender should give better results.

**Comment by luboslenco** [comment] 2021-01-27 17:05
Pushed a fix at https://github.com/armory3d/armorpaint/commit/6ff8fc7f1b3158f0e8050146752d2db4ece2c0dd.

**Closed by luboslenco** 2021-01-27 17:05 UTC
Labels: bug
